import Header from "./Components/Header";
import SessionWrapper from "./Components/SessionWrapper";
import "./globals.css";
export const metadata = {
  title: "Instagram Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body>
          <Header />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
